<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/taca/blob/main/prop/unidad_didac/visualizacion/2_seaborn/visualizing_categorical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

# Dataset de datos meteorológicos de Carmen de Viboral

In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('DatosEstacion2020-01-30.csv')
df.head(2)

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
0,2020-01-30 00:00:00,O,1408,29919,699,62,632,0,1,234,...,0,0,818,6,45,618,1809,10,13,7814
1,2020-01-30 00:01:00,O,1409,29918,699,62,632,0,1,234,...,0,0,818,6,45,618,1809,10,13,33628

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tiempo Sistema               1440 non-null   object
 1   Bar Trend                    1440 non-null   object
 2   Next Record                  1440 non-null   int64
 3   Barometer                    1440 non-null   int64
 4   Inside Temperature           1440 non-null   int64
 5   Inside Humidity              1440 non-null   int64
 6   Outside Temperature          1440 non-null   int64
 7   Wind Speed                   1440 non-null   int64
 8   10 Min Avg Wind Speed        1440 non-null   int64
 9   Wind Direction               1440 non-null   int64
 10  Extra Temperatures           1440 non-null   int64
 11  Soil Temperatures            1440 non-null   int64
 12  Leaf Temperatures            1440 non-null   int64
 13  Outside Humidity             1440 non-null   int64
 14  Extra Humidties              1440 non-null   int64
 15  Rain Rate                    1440 non-null   int64
 16  UV                           1440 non-null   int64
 17  Solar Radiation              1440 non-null   int64
 18  Storm Rain                   1440 non-null   int64
 19  Start Date of current Storm  1440 non-null   int64
 20  Day Rain                     1440 non-null   int64
 21  Month Rain                   1440 non-null   int64
 22  Year Rain                    1440 non-null   int64
 23  Day ET                       1440 non-null   int64
 24  Month ET                     1440 non-null   int64
 25  Year ET                      1440 non-null   int64
 26  Soil Moistures               1440 non-null   int64
 27  Leaf Wetnesses               1440 non-null   int64
 28  Inside Alarms                1440 non-null   int64
 29  Rain Alarms                  1440 non-null   int64
 30  Outside Alarms               1440 non-null   int64
 31  Extra Temp/Hum Alarms        1440 non-null   int64
 32  Soil & Leaf Alarms           1440 non-null   int64
 33  Transmitter Battery Status   1440 non-null   int64
 34  Console Battery Voltage      1440 non-null   int64
 35  Forecast Icons               1440 non-null   int64
 36  Forecast Rule number         1440 non-null   int64
 37  Time of Sunrise              1440 non-null   int64
 38  Time of Sunset               1440 non-null   int64
 39  <LF> = 0x0A                  1440 non-null   int64
 40  <CR> = 0x0D                  1440 non-null   int64
 41  CRC                          1440 non-null   int64
dtypes: int64(40), object(2)
memory usage: 472.6+ KB

In [15]:
df.describe()

,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,Extra Temperatures,Soil Temperatures,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
count,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,1440.0,1440.0,...,1440.0,1440.0,1440.000000,1440.000000,1440.000000,1440.0,1440.000000,1440.0,1440.0,1440.000000
mean,1615.500694,29924.931250,690.849306,60.516667,625.372222,1.715972,1.681250,219.193750,65535.0,65535.0,...,0.0,0.0,818.409028,5.791667,79.500000,618.0,1809.289583,10.0,13.0,32207.004167
std,794.979171,37.492646,90.315909,2.185555,66.420400,2.317536,1.891184,55.457018,0.0,0.0,...,0.0,0.0,0.697500,1.117645,44.476103,0.0,0.453727,0.0,0.0,19090.968677
min,0.000000,29853.000000,591.000000,56.000000,543.000000,0.000000,0.000000,5.000000,65535.0,65535.0,...,0.0,0.0,817.000000,3.000000,45.000000,618.0,1809.000000,10.0,13.0,52.000000
25%,1479.750000,29900.000000,603.000000,58.000000,558.000000,0.000000,0.000000,211.000000,65535.0,65535.0,...,0.0,0.0,818.000000,6.000000,45.000000,618.0,1809.000000,10.0,13.0,15128.500000
50%,1839.500000,29930.000000,663.500000,62.000000,604.000000,1.000000,1.000000,236.000000,65535.0,65535.0,...,0.0,0.0,819.000000,6.000000,75.000000,618.0,1809.000000,10.0,13.0,32427.500000
75%,2199.250000,29958.000000,778.000000,62.000000,697.000000,2.000000,4.000000,238.000000,65535.0,65535.0,...,0.0,0.0,819.000000,6.000000,93.000000,618.0,1810.000000,10.0,13.0,48693.000000
max,2559.000000,29987.000000,850.000000,63.000000,740.000000,12.000000,6.000000,360.000000,65535.0,65535.0,...,0.0,0.0,820.000000,7.000000,187.000000,618.0,1810.000000,10.0,13.0,65513.000000

In [16]:
df.keys()

Index(['Tiempo Sistema', 'Bar Trend', 'Next Record', 'Barometer',
       'Inside Temperature', 'Inside Humidity', 'Outside Temperature',
       'Wind Speed', '10 Min Avg Wind Speed', 'Wind Direction',
       'Extra Temperatures', 'Soil Temperatures', 'Leaf Temperatures',
       'Outside Humidity', 'Extra Humidties', 'Rain Rate', 'UV',
       'Solar Radiation', 'Storm Rain', 'Start Date of current Storm',
       'Day Rain', 'Month Rain', 'Year Rain', 'Day ET', 'Month ET', 'Year ET',
       'Soil Moistures', 'Leaf Wetnesses', 'Inside Alarms', 'Rain Alarms',
       'Outside Alarms', 'Extra Temp/Hum Alarms', 'Soil & Leaf Alarms',
       'Transmitter Battery Status', 'Console Battery Voltage',
       'Forecast Icons', 'Forecast Rule number', 'Time of Sunrise',
       'Time of Sunset', '<LF> = 0x0A', '<CR> = 0x0D', 'CRC'],
      dtype='object')

In [17]:
#drop columns

cols_to_drop = ['Bar Trend', 'Next Record',
    'Inside Temperature', 'Inside Humidity',
    '10 Min Avg Wind Speed', 'Extra Temperatures', 'Soil Temperatures', 'Leaf Temperatures',
    'Extra Humidties', 'Storm Rain', 'Start Date of current Storm',
 #   'Month Rain', 'Year Rain', 'Day ET', 'Month ET', 'Year ET',
    'Day ET', 'Month ET', 'Year ET',
    'Soil Moistures', 'Leaf Wetnesses', 'Inside Alarms', 'Rain Alarms',
    'Outside Alarms', 'Extra Temp/Hum Alarms', 'Soil & Leaf Alarms',
    'Transmitter Battery Status', 'Console Battery Voltage',
    'Forecast Icons', 'Forecast Rule number', 'Time of Sunrise',
    'Time of Sunset', '<LF> = 0x0A', '<CR> = 0x0D', 'CRC'
               ]

In [18]:

df.drop(cols_to_drop, axis=1, inplace = True)
# Apply basic transformations
df['Tiempo Sistema'] = pd.to_datetime(df['Tiempo Sistema']) - pd.to_timedelta(5,unit='h')
df['Rain Rate'] = df['Rain Rate']*0.2/10. #in units of cm/hour
df['Barometer'] = (df['Barometer']/1000.*(3386.389/100.0)) - (1011.0 - 788.0)
df['Outside Temperature'] = ( df['Outside Temperature']/10. - 32.) * (5.0/9.0)
df.loc[(df['Outside Temperature'] > 50) | (df['Outside Temperature'] < -15)] = np.nan
#df.to_sql(name='DatosMeteoro',con=sqlite_connection,index=False,if_exists='append')

In [19]:
df.head()

,Tiempo Sistema,Barometer,Outside Temperature,Wind Speed,Wind Direction,Outside Humidity,Rain Rate,UV,Solar Radiation,Day Rain,Month Rain,Year Rain
0,2020-01-29 19:00:00,790.173725,17.333333,0.0,234.0,86.0,0.0,0.0,0.0,0.0,242.0,6690.0
1,2020-01-29 19:01:00,790.139861,17.333333,0.0,234.0,86.0,0.0,0.0,0.0,0.0,242.0,6690.0
2,2020-01-29 19:02:00,790.173725,17.333333,1.0,234.0,86.0,0.0,0.0,0.0,0.0,242.0,6690.0
3,2020-01-29 19:03:00,790.173725,17.333333,0.0,234.0,86.0,0.0,0.0,0.0,0.0,242.0,6690.0
4,2020-01-29 19:04:00,790.139861,17.333333,0.0,234.0,86.0,0.0,0.0,0.0,0.0,242.0,6690.0